platform :ios, '8.0'

pod 'AFNetworking'
pod 'ChameleonFramework'
pod 'FLAnimatedImage'
pod 'M13ProgressSuite'
pod 'pop'
pod 'SDWebImage'
pod 'SlackTextViewController'
pod 'TMTumblrSDK'
pod 'TMCache'
pod 'VENTouchLock', :git => 'https://github.com/ianyh/VENTouchLock.git'
pod 'WCFastCell'
