platform :ios, '8.0'

pod 'AFNetworking'
pod 'ChameleonFramework'
pod 'CHTCollectionViewWaterfallLayout'
pod 'FLAnimatedImage'
pod 'FontAwesomeKit', :git => 'https://github.com/PrideChung/FontAwesomeKit.git'
pod 'M13ProgressSuite', :git => 'https://github.com/ianyh/M13ProgressSuite.git'
pod 'pop'
pod 'Reachability'
pod 'SDWebImage'
pod 'SlackTextViewController'
pod 'SVPullToRefresh'
pod 'TMTumblrSDK', '~> 1'
pod 'TMCache'
pod 'VENTouchLock'
pod 'WCFastCell'
pod "youtube-ios-player-helper"
